### ISSUE TITLE
Docker issue?

### ISSUE THREAD

**Issue by corvock** [thelounge/docker-lounge#10]
I followed the documented instructions for installation through docker, and while it starts, i am not greeted with a screen to enter any connection information. I simply get https://corvock.net/i/Screenshot-2016205253.png

**Comment by williamboman** [comment]
The docs for Docker deployment are outdated and the `Dockerfile` in `thelounge/lounge` is broken (see https://github.com/thelounge/lounge/pull/237). You can either use the official image on DockerHub;

```sh
$ docker pull thelounge/lounge:1.5.0
```

or build your own one from the Dockerfile in this repo. See https://github.com/thelounge/thelounge.github.io/pull/28 for updated docs.
