### ISSUE TITLE
port environment in README and startup file

### ISSUE THREAD

**Issue by sparklyballs** [thelounge/docker-lounge#19]
In the README file for the docker there is mention of a port environment variable and i see it in the entrypoint file.

With using,

 `--publish 9000:9000`

 in the docker [run command](https://github.com/thelounge/docker-lounge#running-a-container) you would end up with a situation of an internal port change that wasn't published to the host.

The docker way of selecting another port is to change the host side of the publish switch.

ie `--publish 8000:9000` if the user wanted to use 8000 as the port, the docker daemon would handle the port change and map 8000 to the internal port of 9000 kind of similar to NAT on a router.

**Comment by sparklyballs** [comment]
`docker run -d --name=test -p 8000:9000 -v /home/sparklyballs/test:/home/lounge/data thelounge/lounge`

![screen shot 2016-10-16 at 10 18 25](https://cloud.githubusercontent.com/assets/4343808/19416486/e7e93a1c-9389-11e6-9598-f135300c0354.png)

**Comment by williamboman** [comment]
HI @sparklyballs! I'm not understanding what the issue is?

**Comment by sparklyballs** [comment]
In docker you publish a port and that port is opened to the host for use, (or you can use --net=host mode and any and all ports required are made available, but a different story)

if you change the internal port with your port environment setting, docker won't know this and the port won't be available to the host.

Docker gets around this by allowing you to change the host side of any published ports.

The log will still say :9000 though unfortunately, but at least it will still work.

**Comment by sparklyballs** [comment]
pictures speak louder than words...

![screen shot 2016-10-16 at 13 42 21](https://cloud.githubusercontent.com/assets/4343808/19417493/7b3183c6-93a6-11e6-897f-6f8afdabbf7f.png)

![screen shot 2016-10-16 at 13 42 30](https://cloud.githubusercontent.com/assets/4343808/19417495/80562e06-93a6-11e6-9caf-5e8e6985c7a1.png)

**Comment by williamboman** [comment]
I'm still not following you :confused:. This is working as intended.

**Comment by sparklyballs** [comment]
the information is misleading in your readme.

if a user were to use both `--publish 9000:9000` and `-e PORT=8000` (random port chosen, but could be anything other than 9000) docker will have only opened port 9000 to be seen by the host and results in page not found if trying to use port 8000

you can either instruct users to use the docker way of `--publish 8000:9000` or inform them that they need to change the ports in the `--publish` switch to match the PORT variable, or it won't work.

**Comment by williamboman** [comment]
> if a user were to use both --publish 9000:9000 and -e PORT=8000 (random port chosen, but could be anything other than 9000) docker will have only opened port 9000 to be seen by the host and results in page not found if trying to use port 8000

Sure, but that doesn't make any sense though. The only real use case of using `PORT` is when you run the container in host networking mode (and thus removing the need to publish any ports).

If you want to set `PORT` and still run the container with bridged networking you'd of course have to change the container port as well, so;

```sh
$ docker run -e PORT=15000 -p 8000:15000 thelounge/lounge
# same thing as
$ docker run -p 8000:9000 thelounge/lounge
```

But then again, that doesn't make any sense.

> the information is misleading in your readme.

I don't agree here. I think it's implied one would have to change the published container port if one changes the port lounge listens on.

**Comment by sparklyballs** [comment]
"Sure, but that doesn't make any sense though. The only real use case of using PORT is when you run the container in host networking mode (and thus removing the need to publish any ports)."

would be great, but your readme doesn't mention that anywhere.

"I don't agree here. I think it's implied one would have to change the published container port if one changes the port lounge listens on."

that's assuming your user is savvy about docker.

**Comment by williamboman** [comment]
I see. The `PORT` environment can be a bit dubious, I'll try to clarify things more in the README.
