### ISSUE TITLE
automation

### ISSUE THREAD

**Issue by rgarrigue** [thelounge/docker-lounge#26]
Hi

I'm trying to automate lounge's deployment with ansible (along with a lot of other stuff part of my personnal cloud).

My problem is, I can't run a command against this docker. For example I tried to create an user like this, before starting a HTTPS / HTTP/2 ready Lounge. 

    ➜  playbooks git:(master) docker run --name lounge --volume /srv/thelounge/users/:/home/lounge/data/users:rw thelounge/lounge --entrypoint='echo onepassword | lounge add oneguy' 
    2017-01-22 14:32:22 [INFO] Config created: /home/lounge/data/config.js
    2017-01-22 14:32:24 [INFO] The Lounge v2.1.0 is now running
    2017-01-22 14:32:24 [INFO] Available on: http://*:9000/ in public mode
    2017-01-22 14:32:24 [INFO] Press ctrl-c to stop

Either as a command or an entrypoint, that's a fail.

Why do I wanna do this ? Simply because running thelounge with a HTTPS enabled config.json crash the container straight away without a first user : 

    ➜  playbooks git:(master) docker exec -ti irc 'echo passwd | lounge add guy irc'                                                                                             
    Error response from daemon: Container b0dc260475df5d34daeeb1eb1cc1aa024e0d3837c803de471e1de1cef0658c6f is restarting, wait until the container is running
    ➜  playbooks git:(master) docker logs irc
    22-01-2017 14:17:50 [WARN] No users found!
    22-01-2017 14:17:50 [INFO] Create a new user with 'lounge add <name>'.

(restarting because I said restart unless stopped)

So either I want to be able to run a one shot lounge docker to generate a user... or I'ld like a stable without user https lounge, which would allow me to docker exec afterward. Or let's dream, a web lounge api :-)

Best regards,

**Comment by williamboman** [comment]
Hey @rgarrigue. Have you tried the following:

```sh
$ ls /lounge
my-entrypoint.sh config.js users/ logs/
$ cat /lounge/my-entrypoint.sh
#!/bin/sh

echo foo | lounge add Test
# other custom stuff here

# proceed with the default entrypoint
docker-entrypoint.sh # docker-entrypoint.sh is located in /usr/local/bin and thus in the container's PATH
$ docker run --name lounge -v /lounge:/home/lounge/data --entrypoint /home/lounge/data/my-entrypoint.sh thelounge/lounge
```

**Comment by williamboman** [comment]
Hey again, #28 will fix your initial issues. It'll make it possible to customize the command to be executed by the container, e.g.;

```sh
$ docker run -ti --rm -v ~/.lounge:/home/lounge/data thelounge/lounge 'echo passwd | lounge add Foo'
```

**Comment by rgarrigue** [comment]
Thanks !

**Comment by williamboman** [comment]
I haven't decided whether I'll immediately do a secondary `2.2.0` release that includes that PR or wait until next version bump of `thelounge` though, so it won't be available immediately. https://github.com/thelounge/docker-lounge/issues/26#issuecomment-274341765 is a possible solution if it's urgent.

**Comment by rgarrigue** [comment]
Nope, I made it manually to get started. Will wait for the release to
automate this fully.

2017-02-02 17:29 GMT+01:00 William Boman <notifications@github.com>:
