### ISSUE TITLE
Set up correct .lounge_home at install time

### ISSUE THREAD

**Issue by xPaw** [thelounge/docker-lounge#34]
Thanks to https://github.com/thelounge/lounge/pull/1416, `lounge add <user>` and others can now work correctly without using `LOUNGE_HOME` or (deprecated) `--home`, by setting the correct path in `.lounge_home`.

This will be valid as of v2.5.0.

**Comment by williamboman** [comment]
> by setting the correct path in .lounge_home

If installed via `$ npm install -g thelounge`, would you have to change `/usr/local/lib/node_modules/thelounge/.lounge_config`?

**Comment by xPaw** [comment]
Sounds like that, yes. Perhaps for consistency you should use `--prefix` in `install` to control where lounge gets installed.

https://github.com/thelounge/deb-lounge/blob/17fb69791afaf9773b62121e7dc1b2efb1d68552/build-package#L14

**Comment by williamboman** [comment]
The container currently sets `LOUNGE_HOME`, that's not deprecated is it?

**Comment by xPaw** [comment]
It's not, however using `.lounge_home` should be the most consistent way.

**Comment by astorije** [comment]
Currently, do people need to set `LOUNGE_HOME` when using `lounge add <user>`? If so, then `.lounge_home` will indeed make this more convenient.

**Comment by williamboman** [comment]
> Currently, do people need to set LOUNGE_HOME when using lounge add <user> with Docker?

Nope. It's set ["globally"](https://github.com/thelounge/docker-lounge/blob/master/Dockerfile#L6) in the container environment.

**Comment by williamboman** [comment]
I'm closing as the containers already have `LOUNGE_HOME` set.
