### ISSUE TITLE
REQ: Allow for pre/next build

### ISSUE THREAD

**Issue by EnorMOZ** [thelounge/docker-lounge#42]
It would be nice to have a tag or use a env var to get the pre/next version to test via docker.

**Comment by williamboman** [comment]
This is already possible via the build arg (`THELOUNGE_VERSION`)[https://github.com/thelounge/docker-lounge/blob/master/Dockerfile#L3].

**Comment by lcasey001** [comment]
Sorry for my ignorance how would you do it via docker compose or via ansible docker_container? I tried setting an env var of THELOUNGE_VERSION to "next" and that didn't work. Would I need to use the exact pre verison like v2.7.0-pre.4 ?

**Comment by EnorMOZ** [comment]
Sorry for my ignorance how would you do it via docker compose or via ansible docker_container? I tried setting an env var of THELOUNGE_VERSION to "next" and that didn't work. Would I need to use the exact pre verison like v2.7.0-pre.4 ?

**Comment by williamboman** [comment]
It's not a traditional environment variable, but a build-time variable (see https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables-build-arg).

**Comment by lcasey001** [comment]
Ok so basically I would have to fork it then build it by changing that arg ? Using something like dockerhub then in ansible point to that image instead ?

**Comment by EnorMOZ** [comment]
Ok so basically I would have to fork it then build it by changing that arg ? Using something like dockerhub then in ansible point to that image instead ?

**Comment by williamboman** [comment]
Not sure how ansible works, but in essence:

```sh
$ git clone https://github.com/thelounge/docker-lounge.git
$ cd docker-lounge
$ docker build -t thelounge:next --build-arg THELOUNGE_VERSION=next .
```

**Comment by EnorMOZ** [comment]
Thanks for the help. That did it. I was able to incorporate it into my ansible job. I also found that you have to set pull to no in ansible for it to look at the local registry. Thanks again !!
