### ISSUE TITLE
Ident doesn't work in docker

### ISSUE THREAD

**Issue by ghost** [thelounge/docker-lounge#51]
Using thelounge/lounge:2.7.1

Response to ident (builtin) requests always is 'ERROR : NO-USER', maybe because it tries to match the IP addresses in identification.js

**Comment by ihatemicrosoft-was-already-taken** [comment]
It seems that ident works if you run the container with `--network host`. Maybe that helps someone for a workaround?

**Comment by xPaw** [comment]
I think this will be fixed by https://github.com/thelounge/thelounge/pull/2959
